const countriesList = [
  { name: 'Afghanistan', id: 'WAsBRMWQjYzsr4F1gW3ie' },
  { name: 'Åland Islands', id: 'CyEzuXc-I3Vp_zcA9i6WF' },
  { name: 'Albania', id: 'j1uOtqNnV4uT2ARHlCYtB' },
  { name: 'Algeria', id: 'v7WVipIgTVN8lGrdiLu80' },
  { name: 'American Samoa', id: '67ZpQndc9gxBVWfI92fix' },
  { name: 'Andorra', id: '-iQHHpRclEN9rQzR3pBoj' },
  { name: 'Angola', id: 'rfMB9j5_aRJigcHrUnxMx' },
  { name: 'Anguilla', id: 'rVvc7gygMP3UEED2HTahl' },
  { name: 'Antarctica', id: 'rxTn0MmbX2PUa4cm_0L6x' },
  { name: 'Antigua and Barbuda', id: 'KMJK3NwnJTJ_LkW9cVrms' },
  { name: 'Argentina', id: 'Wi235MNxvtWEk9gKyw15z' },
  { name: 'Armenia', id: 'TwXX1d6aXkMZUUHbvdNdP' },
  { name: 'Aruba', id: '9J5wS_dlOI2YCBvgoyTEh' },
  { name: 'Australia', id: 'MB_KhlhmgS7grh_sVdzx1' },
  { name: 'Austria', id: '_L5lFtdhyPEO3gkgJWGeV' },
  { name: 'Azerbaijan', id: 'yanKBLs1CJIKG6CtkEcoi' },
  { name: 'Bahamas', id: '55qYFAfDWE1AKkJl36X9a' },
  { name: 'Bahrain', id: '6VhOY1mHxkNTnjB6iw813' },
  { name: 'Bangladesh', id: 'rlYhOLl_pB9KCafdOqsf_' },
  { name: 'Barbados', id: '2LL9eFDpM1c78Dsj3Pjaq' },
  { name: 'Belarus', id: 'isV1acg4SLha6a_31ljwI' },
  { name: 'Belgium', id: 'mlh1a7IQN0zxMYpk_IUg1' },
  { name: 'Belize', id: '2MaLhdLlKFmJn9DzM6BPl' },
  { name: 'Benin', id: 'wXcTsFiDnEaT3GcImuOPM' },
  { name: 'Bermuda', id: '3EyQWSPQWkQjabacQuFgU' },
  { name: 'Bhutan', id: 'ZKy_u8YmtFT6kFygqlIok' },
  { name: 'Bolivia (Plurinational State of)', id: 'zJZ6Y-x6p63cX82aTqr75' },
  { name: 'Bonaire, Sint Eustatius and Saba', id: 'qrUQcHcKSgrhS8M5lcPLD' },
  { name: 'Bosnia and Herzegovina', id: '5oUZD537GftVstfouLfKu' },
  { name: 'Botswana', id: 'i9j9k5nzPCrqArQcwQjTW' },
  { name: 'Bouvet Island', id: 'tOQ50F_dt6exvte-4E81g' },
  { name: 'Brazil', id: 'f34Rc3RVzqaXW8E_6SakC' },
  { name: 'British Indian Ocean Territory', id: 'DZIGjE5NYNGvtNWqBL13p' },
  { name: 'United States Minor Outlying Islands', id: 'mSsUzVbminIbQu1njYi6c' },
  { name: 'Virgin Islands (British)', id: 'QteTddve8phQVSIJWVmm8' },
  { name: 'Virgin Islands (U.S.)', id: 'NxCoVFSdriDt5e2WJy2mG' },
  { name: 'Brunei Darussalam', id: 'TJCGa0zjVB6ZFAUsRBBf9' },
  { name: 'Bulgaria', id: '1I0ZqtYtEEXC3MAuxBDJx' },
  { name: 'Burkina Faso', id: 'XGPpDYkFSFmYfRFZfC8v1' },
  { name: 'Burundi', id: 'tgHvlblGY1XHnHlVtTbUZ' },
  { name: 'Cambodia', id: '5CLURnm22kqhvj1V1hMXR' },
  { name: 'Cameroon', id: '8t4bb1iqF6DtynSkmjfYT' },
  { name: 'Canada', id: 's46WXTLDusKrIuZUZjRRe' },
  { name: 'Cabo Verde', id: 'EKGn7y6Gv1Vw83F5spZZu' },
  { name: 'Cayman Islands', id: 'SlAaPDrA0ZLkl7L1WWkse' },
  { name: 'Central African Republic', id: 'AHFaAnrOyY5nTlav6WIhJ' },
  { name: 'Chad', id: 'S567y4DprIWw_jOrmUHsu' },
  { name: 'Chile', id: 'WGb2w-r6I2Shmlw_LzmK3' },
  { name: 'China', id: 'uoUZ8HM7QzdARBzWuZcGA' },
  { name: 'Christmas Island', id: '8dg2A5yV9klT-rnz9fiRa' },
  { name: 'Cocos (Keeling) Islands', id: 'c1Hzae3xqW_rZNRcUObjn' },
  { name: 'Colombia', id: '9mVWZD8K42tDc2VcryurU' },
  { name: 'Comoros', id: 'Kkh7NXkPpvIpiTyufEaZp' },
  { name: 'Congo', id: '7aS6mVdxH3SkvA2dizuh4' },
  { name: 'Congo (Democratic Republic of the)', id: 'UDhvA38aeWX95J0DIUKl2' },
  { name: 'Cook Islands', id: 'Pd-4xHO9BR-x86LDqgbwU' },
  { name: 'Costa Rica', id: '6iAwdbyMj4cD84MXFfmkN' },
  { name: 'Croatia', id: 'pXwYmIkm8Wm0CnvgmUxs5' },
  { name: 'Cuba', id: 'ffqEuSx5Wk5T7NVfk26PE' },
  { name: 'Curaçao', id: 'v75NBCn-ordD25_0G1A75' },
  { name: 'Cyprus', id: 'atpaIWanRpmbaCDYtc40S' },
  { name: 'Czech Republic', id: 'FCuX7vXU5xUUNcE5hqgYn' },
  { name: 'Denmark', id: 'Y4NWQAnL9-TXqFurHH0nc' },
  { name: 'Djibouti', id: 'WXHEe2IqEB3-2k8YAinjB' },
  { name: 'Dominica', id: 'RMuP2ph1RSThUiXJ-j33d' },
  { name: 'Dominican Republic', id: 'lspgSAD30ZFsNMpGrpU26' },
  { name: 'Ecuador', id: 'p9ImMr0NVJg3sruHEoH-I' },
  { name: 'Egypt', id: 'laHRnNHvX8G_D2TmmdlJu' },
  { name: 'El Salvador', id: 'uzZ4X2c3e66aBWLVFtlqk' },
  { name: 'Equatorial Guinea', id: 'NVa6mswhCHWid-Z5a4fan' },
  { name: 'Eritrea', id: 'KVnPUzoD9nS-KkSZFQ09b' },
  { name: 'Estonia', id: 'U8mtM7eSdhMaKm7CtsAUw' },
  { name: 'Ethiopia', id: 'jPSxXCaQjWrNlXuiR6mLZ' },
  { name: 'Falkland Islands (Malvinas)', id: 'BUd_m_SDuO9jJH5YhjCoc' },
  { name: 'Faroe Islands', id: 'jgOfG9eIXFrrxlUw3998K' },
  { name: 'Fiji', id: '1lZ6KQh7ypB0WYqz_AQ5L' },
  { name: 'Finland', id: 'y7BqpGyvsBWda54D1NeT6' },
  { name: 'France', id: 'yXeUeAJkZTfOr-TF3ReZq' },
  { name: 'French Guiana', id: 'o7EUEnTkeJyeqc8Rqx6Mh' },
  { name: 'French Polynesia', id: 'I9ur7i_QonsKofXBbmu0w' },
  { name: 'French Southern Territories', id: '_dKUICVm3ln0tZrGjzsok' },
  { name: 'Gabon', id: 'UZ2ybbCcK5hDwTDduSilb' },
  { name: 'Gambia', id: 'T1cwdcaYrTBqdDjkJQ0KR' },
  { name: 'Georgia', id: 'N8Vz6fEBHSkxRlm4Dkba-' },
  { name: 'Germany', id: 'uh4WWDH-4zWsDi4iqIumK' },
  { name: 'Ghana', id: 'DdcDsDs1cYwDlZv0YUb-l' },
  { name: 'Gibraltar', id: 'mewjlLjrmCjPTBga68uG1' },
  { name: 'Greece', id: 'xAbPxu6rrzwPy27aJeAf9' },
  { name: 'Greenland', id: 'WNOejgAY-fvh8wOu-muhS' },
  { name: 'Grenada', id: 't3pafb_8ZjMadhGyiaqsr' },
  { name: 'Guadeloupe', id: 'NS9D02Gk0oas6B78c4keF' },
  { name: 'Guam', id: 'YLDrSkngtDftA_iOmYwzH' },
  { name: 'Guatemala', id: 'mg8SaC3e0lderJjQzcaSB' },
  { name: 'Guernsey', id: 'lNGm2tkxrijX06zsiHUvE' },
  { name: 'Guinea', id: 'YdZ66IsdwIKtfqXka0i46' },
  { name: 'Guinea-Bissau', id: 'bZYdxW-l_cR1eptDdQfYt' },
  { name: 'Guyana', id: 'zsXIcNZXIkblOrQ9EnmUs' },
  { name: 'Haiti', id: 'S-2L8ab6Fjtv0XOnhdjLT' },
  { name: 'Heard Island and McDonald Islands', id: '8A_jFw7NUbB11LP_caOsD' },
  { name: 'Holy See', id: 'Ba9gCBK4XthR1b0qEKgpd' },
  { name: 'Honduras', id: 'HLlZjQKKWxt7u3Fyb47Yr' },
  { name: 'Hong Kong', id: '7KpwF1fKrthQ7lyRCQ9JL' },
  { name: 'Hungary', id: 'tXQ3VNPQKoLUib9tZh8Ah' },
  { name: 'Iceland', id: 'wMSncc4mHYU94XNXedel4' },
  { name: 'India', id: 'TTE7AO-86pb6S9xbdGcEu' },
  { name: 'Indonesia', id: 'KN7PJEmfKOqZOMYKKuKVX' },
  {
    name: "Côte d'Ivoire,Iran (Islamic Republic of)",
    id: '_mrfUwCekKTAkBEuIH_gX',
  },
  { name: 'Iraq', id: '5yBlawlVUyjisCWRbq3pM' },
  { name: 'Ireland', id: '9fzSGvNXL7rbsOdRPV6zG' },
  { name: 'Isle of Man', id: 'GUiVcCvIY2xeTyk76cCK3' },
  { name: 'Israel', id: 'MVXi41adkhWvTCjH1UiEs' },
  { name: 'Italy', id: '_i4wcPsYISmh8v6k2Wh77' },
  { name: 'Jamaica', id: 'mz_iW7wGdbRbz7bptpN7W' },
  { name: 'Japan', id: 'DhGqDiZBNIUdGPjcUJL7f' },
  { name: 'Jersey', id: '0dzHg7KPe0pf7VLorPzw9' },
  { name: 'Jordan', id: '-mjsJKNuFFVOkRCnpdcQv' },
  { name: 'Kazakhstan', id: '4y8pzuwTCbylIuxI9VwQT' },
  { name: 'Kenya', id: 'Yi5vPS9zZP60U2Wm11OeD' },
  { name: 'Kiribati', id: '9TReOjRIjUtRmqvRU_zT6' },
  { name: 'Kuwait', id: 'qbbVAexyuS-K5zsCH-ryM' },
  { name: 'Kyrgyzstan', id: '1-w2PZK9a--krXeYQHtGN' },
  { name: "Lao People's Democratic Republic", id: 'WBN5nGywiG8IrWwdpqZHL' },
  { name: 'Latvia', id: 'gl7wy_BW_bdPf8yWpnc7o' },
  { name: 'Lebanon', id: 'chGMzA4uTRkfTdxtPebjM' },
  { name: 'Lesotho', id: 'mh0p0zM2tHMcwqVBLooxs' },
  { name: 'Liberia', id: 'eXFgwIwf6acnPqOf813Ap' },
  { name: 'Libya', id: 'Xgo0wsn3-v9TF4yYErZj7' },
  { name: 'Liechtenstein', id: 'UkVSHG1E75mhVQRWkK6KF' },
  { name: 'Lithuania', id: '72dsISWs6yJe2w9cdBjdE' },
  { name: 'Luxembourg', id: 'MM8NONEoTSBCgxlAZBzGt' },
  { name: 'Macao', id: '6H3bcdIBg-ycVTKhEYaXW' },
  {
    name: 'Macedonia (the former Yugoslav Republic of)',
    id: '_45k1XVql1FnYWJqNDG_G',
  },
  { name: 'Madagascar', id: 'rRwtAuAzphHjfNXeqtYy0' },
  { name: 'Malawi', id: 'M9Qq08E3aqm5JWM8POcn8' },
  { name: 'Malaysia', id: 'bBZgIEkTj1m-CgWPKpsSV' },
  { name: 'Maldives', id: '1DOwDRFmiYRoT4voQnVyV' },
  { name: 'Mali', id: 'xAd7Q34hSumTi5vufC2W_' },
  { name: 'Malta', id: 'PqJCjVBHQ4axKJoOdSr8l' },
  { name: 'Marshall Islands', id: '3yImtelMBfPNY0Hb1bB-a' },
  { name: 'Martinique', id: 'yrVSO0yNubB1n_Ml9g5RH' },
  { name: 'Mauritania', id: 'B5ZpwahILCpxO9nPzwDM6' },
  { name: 'Mauritius', id: 'eU9AFxyS0U3dG2o9NkcnK' },
  { name: 'Mayotte', id: 'Lxm5ay65PNbNCOjJH85Zk' },
  { name: 'Mexico', id: '-BQUvXTAf6j9mYI9YuDzQ' },
  { name: 'Micronesia (Federated States of)', id: 'P0eXUa69S-0N6WJs0M7ct' },
  { name: 'Moldova (Republic of)', id: 'ql2waaxoSbtGDM4f8fK1F' },
  { name: 'Monaco', id: 'E7aj4y2xteSSyDYI7Cc1j' },
  { name: 'Mongolia', id: 'wkUdjkkkysHtHtRqWvpsE' },
  { name: 'Montenegro', id: 'pzHXnQi1EBHkplWeJD8JL' },
  { name: 'Montserrat', id: 'tpyzTH3p-Nh_sNwUjgPUl' },
  { name: 'Morocco', id: '0yQ77tEYUyTXKrL7ZfAcc' },
  { name: 'Mozambique', id: 'PvpClDKZqTuekj-c-ynkb' },
  { name: 'Myanmar', id: 'EQrndZDO1FM1AizNitnQ2' },
  { name: 'Namibia', id: 'ha5uaQ_vFqLgS4AAaE0g6' },
  { name: 'Nauru', id: 'fLUqrIoNDDuextnTncxn9' },
  { name: 'Nepal', id: '1YlOeWslHLw9oSlaGUps0' },
  { name: 'Netherlands', id: '3Nm2F1E91U7sdlzdCXF3g' },
  { name: 'New Caledonia', id: 'eb8uhxx76P-9-929CBZdS' },
  { name: 'New Zealand', id: 'lLd_Ah1v6bY_uJU_1ax1r' },
  { name: 'Nicaragua', id: 'XEdCcl5rzj4cFqZKjdPeS' },
  { name: 'Niger', id: 'tpP-nEAPt5ELBOXvxjdzS' },
  { name: 'Nigeria', id: '_G_KiqJqFE9DJ2bFTn_j8' },
  { name: 'Niue', id: 'lMhGvdTjuzeM-qtli-9Nv' },
  { name: 'Norfolk Island', id: 'c7-M_3prJyMoJWkEJtRCu' },
  {
    name: "Korea (Democratic People's Republic of)",
    id: '9heXUddPqarkYVp9QEG97',
  },
  { name: 'Northern Mariana Islands', id: 'Ml0xnwMLeW7L9F0r9uI5g' },
  { name: 'Norway', id: 'BPpLF4ONMvw6RIrgSh9LQ' },
  { name: 'Oman', id: 'WaPxX7Oweh5Kema-5DO2w' },
  { name: 'Pakistan', id: 'VWEyMb9s5-cZpx65lbzz9' },
  { name: 'Palau', id: 'K9wviORGGM4tti4YHinr3' },
  { name: 'Palestine, State of', id: 'uWJeVPm_1vaqiKCWOCCEH' },
  { name: 'Panama', id: 'GMCdgyyHqNM3G7v-pWSlu' },
  { name: 'Papua New Guinea', id: 'l5EKuEkHUU6VsOy4rIWwJ' },
  { name: 'Paraguay', id: 'sqknwalKKzk0oohNKbcJZ' },
  { name: 'Peru', id: 'MBv1ygmdb_LIhadcAOy8O' },
  { name: 'Philippines', id: 'kzyFB7LMdOdGJiLbGIvLw' },
  { name: 'Pitcairn', id: '0Z2umDz5zic0BYRWLxycr' },
  { name: 'Poland', id: 'rM3wJnSWlma9rO1gab9YD' },
  { name: 'Portugal', id: 'zKMlIsj5Oirl53gR7eUQE' },
  { name: 'Puerto Rico', id: 'bfkXV79D5d2eJime7Hsjx' },
  { name: 'Qatar', id: 'NP7mJfNN4dsMorCrphfgy' },
  { name: 'Republic of Kosovo', id: 'lwaFivz8btMo1aem5POyo' },
  { name: 'Réunion', id: 'WCEcpEK2kXzr9ILYUb62p' },
  { name: 'Romania', id: 'bAda_av6-Jsn4a66tAhsH' },
  { name: 'Russian Federation', id: 'KAoCC3JdSjY7az4c8_k7Y' },
  { name: 'Rwanda', id: 'RYBGpl3YeKJRyViUMOlaT' },
  { name: 'Saint Barthélemy', id: 'ovRPbHy3JnZuE1ewtUm6o' },
  { name: 'Saint Helena', id: '7RzIQnqS9H6O4mO5COdQH' },
  { name: 'Ascension and Tristan da Cunha', id: 'NojrBQ7YwcnkMKG-GKC7q' },
  { name: 'Saint Kitts and Nevis', id: 'ZgchVd36Q42cVGd9ocmeI' },
  { name: 'Saint Lucia', id: 'hwZgGP64Dz2JhdAZ9rgYq' },
  { name: 'Saint Martin (French part)', id: 'T6RPM0Un_l3ZRvJpx8OCS' },
  { name: 'Saint Pierre and Miquelon', id: '1SofcAhrya57twzbUIz9N' },
  { name: 'Saint Vincent and the Grenadines', id: 'G-X0dva7aLwPj9OVxdJ98' },
  { name: 'Samoa', id: '6BeOl08lrmeP01Nvz3GpO' },
  { name: 'San Marino', id: 'Q6ctgBn1IgvNopLhl4eLP' },
  { name: 'Sao Tome and Principe', id: 'Q-5nH_ibb2CvBdY0WU8Rh' },
  { name: 'Saudi Arabia', id: 'k6CBKdETTO7L9ABGMYtkM' },
  { name: 'Senegal', id: 'qcdRH04lbPpuc1a4BCfe6' },
  { name: 'Serbia', id: 'NeMWMUYZUcIDPZbx2h-AR' },
  { name: 'Seychelles', id: 'ofhGBErhaVrQXRX8ZHNSK' },
  { name: 'Sierra Leone', id: 'wj2W9j4y36bIljP4BHTq4' },
  { name: 'Singapore', id: 'gQZGsXqI4f0kiKZT8B-F3' },
  { name: 'Sint Maarten (Dutch part)', id: '2sc3by3ZBbMM4I8MCZWaz' },
  { name: 'Slovakia', id: 'q9hgdDI4ND4avZCtGVN4z' },
  { name: 'Slovenia', id: 'THMqaKUwGPusGTiwpF2Ah' },
  { name: 'Solomon Islands', id: 'vohK9p7qyV4pawIs1Zbyp' },
  { name: 'Somalia', id: 'vJu40Lj1AbFtWcY_reYMU' },
  { name: 'South Africa', id: 'N9W0Sj8tuC2RWrh4EMKk3' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    id: 'zwqBgnsqsxnzcyl_Er2Zu',
  },
  { name: 'Korea (Republic of)', id: 'wzFcjbz1lKgmdqnbVrktq' },
  { name: 'South Sudan', id: 'PcCOdgD1-qiuOF5-r5rBf' },
  { name: 'Spain', id: 'HGDifNfh2hi6-mpgBoo6r' },
  { name: 'Sri Lanka', id: 'PLK8fiuqLoQFmUaFTId18' },
  { name: 'Sudan', id: '5ofV0c7jUb_d-XEQkasOP' },
  { name: 'Suriname', id: '9nCJuzJZlvpXQq_ka14Nk' },
  { name: 'Svalbard and Jan Mayen', id: 'nNZK6VuLJD22J09Y2Ibb7' },
  { name: 'Swaziland', id: 'mKLVVM5wOQYnDZQ5IahXs' },
  { name: 'Sweden', id: 'iJZj0q2lKnui9_H-MWzBu' },
  { name: 'Switzerland', id: 'FlnUc0FpfKsISAaoKkVGq' },
  { name: 'Syrian Arab Republic', id: 'nTbofd2HF5FhdLfsxlpOF' },
  { name: 'Taiwan', id: 'MmzE2RV0uLLowA1udVS8r' },
  { name: 'Tajikistan', id: 'tOTOSu-Dk5pq9qV_p68Dp' },
  { name: 'Tanzania, United Republic of', id: 'C3mqaO7BOb-8zZ0Z2v69T' },
  { name: 'Thailand', id: 'J6WD1ldIO1rGkyoEsSjf5' },
  { name: 'Timor-Leste', id: 'Y_0fmtL6k2uY3mQtvAcHb' },
  { name: 'Togo', id: 'Bs8zmBlk5Tg4rxTTse9ku' },
  { name: 'Tokelau', id: 'YRBPM7tuFr5sUD6mbNK7J' },
  { name: 'Tonga', id: 'WpCBjyhhb3m-SUySx1WPg' },
  { name: 'Trinidad and Tobago', id: 'NITGnULbZZJgG_mmcXiJQ' },
  { name: 'Tunisia', id: '5BxhHh-QnjYVli-ygMgTv' },
  { name: 'Turkey', id: 'x96ZhdU_NYw75ULwWBIX1' },
  { name: 'Turkmenistan', id: 'PHz5GL5vW7LZypLWDp4Uf' },
  { name: 'Turks and Caicos Islands', id: 'PwmBm1KqticSegGCXT8fX' },
  { name: 'Tuvalu', id: '3Wam1DwPPQ8XLn--srI51' },
  { name: 'Uganda', id: 'DatTH0CXmnQdVpdINjMOT' },
  { name: 'Ukraine', id: 'DOPx_poI8zytnrIUaMClx' },
  { name: 'United Arab Emirates', id: 'nTHwzBKnFAzRKSXrOX3xG' },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    id: 'zqmlKGdNX9Jm86xyiFk7L',
  },
  { name: 'United States of America', id: 'VRvNxdV6Tp3sWb_42TMkp' },
  { name: 'Uruguay', id: 'HoIAVTiPTNOjcfP2u3ktu' },
  { name: 'Uzbekistan', id: 'NvFVREmkjKewGNdqndURZ' },
  { name: 'Vanuatu', id: '7Ai9NViSdmljX6NJXSzLQ' },
  { name: 'Venezuela (Bolivarian Republic of)', id: 'PT2ma4iGEZNI94cjD5kCz' },
  { name: 'Viet Nam', id: 'uNKwTy96jy4glEsP2evfz' },
  { name: 'Wallis and Futuna', id: '57uX8hRPp_L_4w4gmXjKt' },
  { name: 'Western Sahara', id: 'l8NlBXt4s1wOh5yUt32I_' },
  { name: 'Yemen', id: '9CkCd7bhocx5YS10rzCn5' },
  { name: 'Zambia', id: 'URlc7x4Hex8wfBJ2YCdjZ' },
  { name: 'Zimbabwe', id: 'HeRODSNJQO5Nv4g3erbd0' },
]

export default countriesList
